name: JSON Validator
on:
  workflow_dispatch:
  push:
    paths:
      - "src/main/resources/**.json"
  pull_request:
    types: [opened, reopened, edited]
    paths:
      - "src/main/resources/**.json"

jobs:
  Validate-JSON:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: JSON Validation - Languages
        uses: ammarlakis/action-ajv@v1.0.0
        with:
          schema: "./.github/schemas/lang.schema.json"
          data: "src/main/resources/assets/changed/lang/*.*"
          allErrors: true
